///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LocationReportData {
/*
{
  "staff_id": 33,
  "staff_name": "Hussain",
  "total_hours": 10,
  "total_minutes": 0
} 
*/

  int? staffId;
  String? staffName;
  int? totalHours;
  int? totalMinutes;

  LocationReportData({
    this.staffId,
    this.staffName,
    this.totalHours,
    this.totalMinutes,
  });
  LocationReportData.fromJson(Map<String, dynamic> json) {
    staffId = json['staff_id']?.toInt();
    staffName = json['staff_name']?.toString();
    totalHours = json['total_hours']?.toInt();
    totalMinutes = json['total_minutes']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['staff_id'] = staffId;
    data['staff_name'] = staffName;
    data['total_hours'] = totalHours;
    data['total_minutes'] = totalMinutes;
    return data;
  }
}
